---
- name: User Playbook
  hosts: all
  become: yes
  become_method: sudo
  user: centos
  tasks:
  - name: User add
    user:
      name: Bob
      comment: "John Smith"
      groups: wheel
      generate_ssh_keys: yes
      state: present

  - name: Add user lisa
    user:
      name: lisa
      state: absent    