---
- name: Installs Packages
  hosts: all
  become: yes
  become_method: sudo
  user: centos
  tasks:
  - name: Install wordpress
    get_url:
      url: https://wordpress.org/latest.tar.gz
      dest: .
  
  - name: Unarchive wordpress
    unarchive:
      src: wordpress-5.4.1.tar.gz
      dest: .