---
- name: Install Wordpress
  hosts: all
  become: yes
  become_method: sudo
  user: centos
  tasks:
  - name: Download wordpress
    get_url:
      url: https://wordpress.org/latest.tar.gz
      dest: .
  
  - name: Unarchive wordpress
    unarchive:
      src: wordpress-5.4.1.tar.gz
      dest: .
      remote_src: yes

  - name: Install packages
    package:
      name: "{{item}}"
      state: present
    with_items:
    - telnet
    - httpd
    - mysql
    - epel-release
    - yum-utils
    - mariadb
    - mariadb-server
    - MySQL-python

  - name: Copy file with owner
    copy:
      src: wordpress/
      dest: /var/www/html/
      owner: apache
      group: apache
      remote_src: yes

  - name: Restart httpd
    service:
      name: httpd
      state: started
      enabled: true

  - name: Disable SELinux
    selinux:
      state: disabled

  - name: Starting mariadb
    service:
      name: mariadb
      state: started
      enabled: yes

  - name: Creating a user
    mysql_user:
      user: admin
      password: mysecure
      priv: '*.*:ALL,GRANT'
      state: present

  - name: Creating wordpress
    mysql_db:
      name: wordpress
      state: present

  - name: Install epel
    shell: "sudo yum install http://rpms.remirepo.net/enterprise/remi-release-7.rpm -y"
  - name: config manager enabled 
    shell: "sudo yum-config-manager --enable remi-php73"
  - name : Instal php 
    shell: "sudo yum install php php-mysql -y"


    

